FROM ardoises-server

ADD . /src/ardoises

RUN cd /src/ardoises/  \
 && luarocks make rockspec/ardoises-server-master-1.rockspec \
 && mkdir -p /etc/nginx/ \
 && cp src/ardoises/server/nginx.conf /etc/nginx/nginx.conf \
 && rm -rf /src/ardoises \
 && true
