#! /usr/bin/env bash

mkdir -p /etc/nginx/ssl
openssl rand 48 -out /etc/nginx/ssl/ticket.key
openssl dhparam -dsaparam -out /etc/nginx/ssl/dhparam4.pem

certbot certonly \
  --rsa-key-size 4096 \
  --webroot \
  --webroot-path ./data \
  -d ardoises.ovh

certbot renew \
  --webroot \
  --webroot-path ./data

certbot \
  --non-interactive \
  --agree-tos \
  --email=admin@ardoises.ovh \
  register
certbot \
  certonly \
  --standalone \
  -d "ardoises.ovh"


  -w "/" \
