#! /usr/bin/env bash

mkdir -p /etc/nginx/ssl
openssl rand 48 -out /etc/nginx/ssl/ticket.key
openssl dhparam -out /etc/nginx/ssl/dhparam4.pem

certbot \
  --non-interactive \
  --agree-tos \
  --email=admin@ardoises.ovh \
  register
certbot \
  certonly \
  --standalone \
  -w "/" \
  -d "ardoises.ovh"
